version: '3'

services:
  socket_server:
    build:
      context: .
      dockerfile: Dockerfile_socket_server
    ports:
      - "${PORT}:${PORT}"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - app-network

  processer:
    build:
      context: .
      dockerfile: Dockerfile_processer
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
